include $(TOPDIR)/rules.mk

LUCI_TITLE:=Support for Kernel mode L2TPv3
LUCI_DEPENDS:=+l2tpv3

PKG_MAINTAINER:=Harusame <admin@haru3.me>
PKG_LICENSE:=Apache-2.0

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
